# Generated by Django 2.1.11 on 2020-01-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='user',
        ),
    ]
