# Generated by Django 2.1.11 on 2020-01-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_procedure_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endopolyp',
            name='procedure_id',
        ),
        migrations.AddField(
            model_name='endopolyp',
            name='procedure_id',
            field=models.ManyToManyField(to='procedure.Procedure'),
        ),
    ]
