# Generated by Django 2.1.11 on 2020-01-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_auto_20200120_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endopolyp',
            name='procedure_id',
        ),
        migrations.AddField(
            model_name='endopolyp',
            name='procedure_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Procedure_Polyp', to='procedure.Procedure'),
        ),
    ]
