# Generated by Django 2.1.11 on 2020-01-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_auto_20200120_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='polyp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedure.EndoPolyp'),
        ),
    ]
