# Generated by Django 2.1.11 on 2020-01-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0007_procedure_polyp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='polyp_id',
        ),
    ]
