# Generated by Django 2.1.11 on 2020-01-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0010_auto_20200120_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndoCenter',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=255)),
                ('room_id', models.IntegerField()),
                ('user_registered', models.DateTimeField()),
            ],
            options={
                'db_table': 'endo_center',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EndoEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.IntegerField(blank=True, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'endo_equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EndoMiniclip',
            fields=[
                ('clip_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clip_link', models.CharField(max_length=500)),
                ('equipment_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('polyp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='miniclip_polyps', to='procedure.EndoPolyp')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='miniclip_procedure', to='procedure.Procedure', unique=True)),
            ],
            options={
                'db_table': 'endo_miniclip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EndoPatient',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'endo_patient',
                'managed': True,
            },
        ),
    ]
