# Generated by Django 2.1.11 on 2020-01-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0012_auto_20200120_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='center_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='center', to='procedure.EndoCenter'),
        ),
    ]
