# Generated by Django 2.1.11 on 2020-01-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0014_remove_endocenter_user_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='center_id',
            new_name='center',
        ),
    ]
